### ISSUE TITLE
Build doesn't run

### ISSUE THREAD

**Issue by root-Manas** [Malwarize/webpalm#17] opened 2023-08-12 16:43 UTC
After Installing webpalm using both cloning and direct go installation and try to use the tool using " webpalm -u https://google.com -l1 --live" it just doesn't run. Even tried running on a Docker Container still didn't work.
![image](https://github.com/Malwarize/webpalm/assets/97402139/a1eb953d-7740-457b-bdfb-64da67e8118d)

**Comment by yassin-l** [comment] 2023-08-13 15:32
Hi @root-Manas, this issue is a duplicate of #16, which discusses the same problem. The original issue provides detailed information and ongoing discussions regarding this matter.

You can find [the solution](https://github.com/Malwarize/webpalm/issues/16#issuecomment-1672108953) in the original issue.

**Closed by yassin-l** 2023-08-13 15:32 UTC
